# Generated by Django 3.0.9 on 2020-08-22 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tela',
            name='factor',
        ),
    ]
